services:
  web:
    build: .
    image: victorsantos12/seeds-fastapi:latest
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=SeedsDocker
      - DEBUG=True
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=fastapi_seed
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_seed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: